# Generated by Django 4.2.25 on 2025-10-12 22:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("estudiante", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="estudiante",
            name="edad",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
